//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: cmp.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_cmp_H__
#define __WDR_cmp_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "cmp_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID6_SPLITTER1 = 16000;
wxSizer *WindowFunc6( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID6_TOOLPANEL = 16001;
const int ID6_WGPANEL = 16002;
wxSizer *WgOutputFunc6( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID6_TREEBOOK = 16003;
const int ID6_LINE2 = 16004;
const int ID6_PREVIEW = 16005;
const int ID6_CB_PREVIEW = 16006;
wxSizer *CmpFunc6( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID6_TEXT = 16007;
const int ID6_RISM = 16008;
const int ID6_COMPOSER = 16009;
const int ID6_TITLE = 16010;
const int ID6_PRINTER = 16011;
const int ID6_YEAR = 16012;
const int ID6_LIBRARY = 16013;
const int ID6_BOOK_IMAGES = 16014;
const int ID6_ON_BOOK_IMAGES = 16015;
const int ID6_BOOK_AXFILES = 16016;
const int ID6_ON_BOOK_AXFILES = 16017;
wxSizer *CmpDataFunc6( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID6_MENU_FILE = 16018;
const int ID6_OPEN_CMP = 16019;
const int ID6_MENU_EDIT = 16020;
const int ID6_COLLATOR = 16021;
const int ID6_CMP_EDIT = 16022;
const int ID6_CMP_LOAD = 16023;
const int ID6_PAGE = 16024;
const int ID6_ZOOM_OUT = 16025;
const int ID6_ZOOM_IN = 16026;
const int ID6_ADJUST = 16027;
const int ID6_ADJUST_V = 16028;
const int ID6_ADJUST_H = 16029;
const int ID6_MENU = 16030;
const int ID6_PREVIOUS = 16031;
const int ID6_NEXT = 16032;
const int ID6_GOTO = 16033;
const int ID6_TOOLS = 16034;
wxMenuBar *MenuBarFunc6();

// Declare toolbar functions

const int ID6_COLLATE = 16035;
void ToolBarFunc6( wxToolBar *parent );

// Declare bitmap functions

wxBitmap BitmapsFunc6( size_t index );

#endif

// End of generated file
