//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: edt.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_edt_H__
#define __WDR_edt_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "edt_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID5_LINE = 15000;
const int ID5_TOOLPANEL = 15001;
const int ID5_MUSPANEL = 15002;
wxSizer *WindowFunc5( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID5_NOTATION = 15003;
const int ID5_TEXT = 15004;
const int ID5_STAFF_LINES = 15005;
const int ID5_NB_STAVES = 15006;
const int ID5_RB_SIZE = 15007;
const int ID5_TX_HEIGHT = 15008;
const int ID5_TX_WIDTH = 15009;
const int ID5_RB_ORIENTATION = 15010;
wxSizer *EdtNewDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

// Declare menubar functions

const int ID5_MENU_FILE = 15011;
const int ID5_MENU = 15012;
const int ID5_OPEN_WWG = 15013;
const int ID5_OPEN_MEI = 15014;
const int ID5_OPEN_PAE = 15015;
const int ID5_OPEN_DARMS = 15016;
const int ID5_SAVE_MLF = 15017;
const int ID5_SAVE_WWG = 15018;
const int ID5_SAVE_MEI = 15019;
const int ID5_SAVE_MODEL = 15020;
const int ID5_SAVE_SVG = 15021;
const int ID5_MENU_EDIT = 15022;
const int ID5_PAGE = 15023;
const int ID5_PREVIOUS = 15024;
const int ID5_NEXT = 15025;
const int ID5_GOTO = 15026;
const int ID5_ZOOMOUT = 15027;
const int ID5_ZOOMIN = 15028;
const int ID5_TOOLS = 15029;
const int ID5_VOICES = 15030;
const int ID5_INDENT = 15031;
wxMenuBar *MenuBarFunc5();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
