//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: axoptions.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_axoptions_H__
#define __WDR_axoptions_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "axoptions_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID_NOTEBOOK_OP = 8000;
wxSizer *OptionsDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int IDO_TEXT = 8001;
const int ID_CB_LANGUAGE_OPS = 8002;
const int ID_DOCUMENTS_DIR = 8003;
const int ID_BROWSE_DOCUMENTS_DIR = 8004;
const int ID_WORKING_DIR = 8005;
const int ID_BROWSE_WORKING_DIR = 8006;
const int IDO_LINE = 8007;
const int ID_FONT_NAME = 8008;
const int ID_CHOOSE_FONT = 8009;
const int ID_SC_MUS_SIZE = 8010;
const int ID_SC_MUS_OFFSET = 8011;
const int ID_PANEL_WINKEY = 8012;
const int ID_LYRIC_FONT_NAME = 8013;
const int ID_CHOOSE_LYRIC_FONT = 8014;
const int ID_CB_GRAY_OPI = 8015;
const int ID_CB_REDUCE_OPI = 8016;
const int ID_TC_MAXSIZE_OPI = 8017;
const int ID_CB_NEGATIVE_OPI = 8018;
const int ID_C_IMAGE_BINARIZATION = 8019;
wxSizer *System1DlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID4_CHB_BORDERS_POS = 8020;
const int ID4_CHB_TEXT_POS = 8021;
const int ID4_CHB_TEXT_INIT = 8022;
const int ID4_CHB_STAVES_SEG = 8023;
const int ID4_MARGIN_TOP = 8024;
const int ID4_MARGIN_BOTTOM = 8025;
const int ID4_MARGIN_LEFT = 8026;
const int ID4_MARGIN_RIGHT = 8027;
const int  ID4_BINARIZATION = 8028;
const int ID4_BIN_REGION_SIZE = 8029;
const int ID4_BINARIZATION_SELECT = 8030;
const int ID4_PRE_DEFAULT = 8031;
const int ID4_REC_TYP_MODELS = 8032;
const int ID4_REC_BT_TYP_MODELS = 8033;
const int ID4_REC_MUS_MODELS = 8034;
const int ID4_REC_BT_MUS_MODELS = 8035;
const int ID4_REC_DELAYED = 8036;
const int ID4_REC_LMORDER = 8037;
const int ID4_LMSCALING = 8038;
wxSizer *Rec1DlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID2_SC_CORRY_OPS1 = 8039;
const int ID2_SC_CORRX_OPS1 = 8040;
const int ID2_SC_SUBWINDOW_OPS1 = 8041;
const int ID2_SC_SPLITX_OPS1 = 8042;
const int ID2_SC_SPLITY_OPS1 = 8043;
const int ID2_CH_FILTER1_OPS1 = 8044;
const int ID2_CH_FILTER2_OPS1 = 8045;
const int ID2_CC_INTERP_OPS1 = 8046;
wxSizer *Sup1DlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID0_TEXTPgBin = 8047;
const int ID0_BIN_CHOICE = 8048;
const int ID0_TEXTRgnSize = 8049;
const int ID0_RGN_SIZE_SPINCTRL = 8050;
const int ID0_LINE1 = 8051;
const int ID0_DEACTIVATE_DIALOG_CHECKBOX = 8052;
wxSizer *BinSelectDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
