//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: empty.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_empty_H__
#define __WDR_empty_H__

#ifdef __GNUG__
    #pragma interface "empty_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID0_SCROLLED 10000
#define ID0_DIRECTORIES 10001
wxSizer *WindowFunc0( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define ID0_MENU_FILE 10002
#define ID0_MENU 10003
#define ID0_MENUITEM1 10004
#define ID0_MENU_EDIT 10005
#define ID0_MENUITEM 10006
wxMenuBar *MenuBarFunc0();

// Declare toolbar functions

void ToolBarFunc0( wxToolBar *parent );

// Declare bitmap functions

wxBitmap BitmapsFunc0( size_t index );

#endif

// End of generated file
