//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: about.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_about_H__
#define __WDR_about_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "about_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID0_LOGO = 9000;
const int ID0_TEXT = 9001;
const int TX_APP_VERSION = 9002;
const int ID0_LINE = 9003;
const int TX_APP_BUILD = 9004;
const int ID0_WXWIDGETS = 9005;
const int ID0_TORCH = 9006;
const int ID0_IM = 9007;
const int ID0_WG = 9008;
wxSizer *AboutDlgFunc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

wxBitmap Void( size_t index );

#endif

// End of generated file
