//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: axapp.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_axapp_H__
#define __WDR_axapp_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "axapp_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID_TC_LOG_PROGRESS = 6000;
const int ID_TEXT = 6001;
const int ID_TX_REST_PROGRESS = 6002;
const int ID_GAUGE1_PROGRESS = 6003;
const int ID_TX_MSG2_PROGRESS = 6004;
const int ID_GAUGE2_PROGRESS = 6005;
const int ID_TX_MSG3_PROGRESS = 6006;
const int ID_GAUGE3_PROGRESS = 6007;
const int ID_CB_CLOSE_AT_END = 6008;
wxSizer *ProgressDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_RB_FIRST_GOTO = 6009;
const int ID_RB_LAST_GOTO = 6010;
const int ID_RB_NO_GOTO = 6011;
const int ID_SC_NO_GOTO = 6012;
wxSizer *GotoDlgFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

// Declare menubar functions

const int ID_MENU_FILE = 6013;
const int ID_NEW = 6014;
const int ID_OPEN = 6015;
const int ID_SAVE = 6016;
const int ID_SAVE_AS = 6017;
const int ID_MENU1 = 6018;
const int ID_CLOSE = 6019;
const int ID_MENU2 = 6020;
const int ID_MENU_ENV = 6021;
const int ID_MENU0 = 6022;
const int ID_MENU_EDIT = 6023;
const int ID_UNDO = 6024;
const int ID_REDO = 6025;
const int ID_CUT = 6026;
const int ID_COPY = 6027;
const int ID_PASTE = 6028;
const int ID_MENU_OPTIONS = 6029;
const int ID_MENU_HELP = 6030;
const int ID_HELP = 6031;
const int ID_ABOUT = 6032;
wxMenuBar *MainMenuBarFunc();

// Declare toolbar functions

void MainToolBarFunc( wxToolBar *parent );

// Declare bitmap functions

wxBitmap ToolBarBitmapFunc( size_t index );

wxBitmap EnvBitmapFunc( size_t index );

#endif

// End of generated file
