//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: aximcontrol.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_aximcontrol_H__
#define __WDR_aximcontrol_H__

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

// Declare menubar functions

// Declare toolbar functions

const int ID_CONTROLLER_PREVIOUS = 21000;
const int ID_CONTROLLER_NEXT = 21001;
const int ID_CONTROLLER_ZOOM_OUT = 21002;
const int ID_CONTROLLER_ZOOM_IN = 21003;
const int ID_CONTROLLER_ADJUST_VH = 21004;
const int ID_CONTROLLER_ADJUST_V = 21005;
const int ID_CONTROLLER_ADJUST_H = 21006;
void ViewToolBarFunc( wxToolBar *parent );

// Declare bitmap functions

wxBitmap ViewBitmapsFunc( size_t index );

#endif

// End of generated file
