//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: sup.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_sup_H__
#define __WDR_sup_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "sup_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID2_SPLITTER1 = 12000;
wxSizer *WindowFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID2_TREEBOOK = 12001;
const int ID2_LINE2 = 12002;
const int ID2_PREVIEW = 12003;
const int ID2_CB_PREVIEW = 12004;
wxSizer *SupBookFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID2_TEXT = 12005;
const int ID2_RISM = 12006;
const int ID2_COMPOSER = 12007;
const int ID2_TITLE = 12008;
const int ID2_PRINTER = 12009;
const int ID2_YEAR = 12010;
const int ID2_LIBRARY1 = 12011;
const int ID2_LIBRARY2 = 12012;
const int ID2_BOOK_IMAGES1 = 12013;
const int ID2_ON_BOOK_IMAGES1 = 12014;
const int ID2_BOOK_IMAGES2 = 12015;
const int ID2_ON_BOOK_IMAGES2 = 12016;
const int ID2_BOOK_AXFILES = 12017;
const int ID2_ON_BOOK_AXFILES = 12018;
wxSizer *SupBookDataFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

const int ID_TEXT2 = 12019;
const int ID2_SRC1_B = 12020;
const int ID2_SRC1_C = 12021;
const int ID_LINE2 = 12022;
const int ID2_SRC2_B = 12023;
const int ID2_SRC2_C = 12024;
const int ID2_RESET_ADJ = 12025;
wxSizer *SupAdjustDlgFunc2( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

// Declare menubar functions

const int ID2_MENU_FILE = 12026;
const int ID2_MENU0 = 12027;
const int ID2_NEW_BOOK = 12028;
const int ID2_OPEN_BOOK = 12029;
const int ID2_CLOSE_BOOK = 12030;
const int ID2_SAVE_BOOK = 12031;
const int ID2_SAVE_AS_BOOK = 12032;
const int ID2_EXPORT_IMAGE = 12033;
const int ID2_MENU_EDIT = 12034;
const int ID2_MENU = 12035;
const int ID2_MANUAL_POINTS = 12036;
const int ID2_CANCEL_SUP = 12037;
const int ID2_PROCESS = 12038;
const int ID2_ADJUST_DLG = 12039;
const int ID2_BOOK = 12040;
const int ID2_BOOK_EDIT = 12041;
const int ID2_BOOK_LOAD = 12042;
const int ID2_BOOK_SUP = 12043;
const int ID2_PAGE = 12044;
const int ID2_ZOOM_OUT = 12045;
const int ID2_ZOOM_IN = 12046;
const int ID2_ZOOM_OUT1 = 12047;
const int ID2_ZOOM_IN1 = 12048;
const int ID2_ZOOM_OUT2 = 12049;
const int ID2_ZOOM_IN2 = 12050;
wxMenuBar *MenuBarFunc2();

// Declare toolbar functions

// Declare bitmap functions

wxBitmap BitmapsFunc2( size_t index );

#endif

// End of generated file
