//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: sup.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_sup_H__
#define __WDR_sup_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "sup_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID2_SPLITTER1 = 12002;
wxSizer *WindowFunc2( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID2_MENU_FILE = 12003;
const int ID2_MENU0 = 12004;
const int ID2_OPEN1 = 12005;
const int ID2_OPEN2 = 12006;
const int ID2_MENU_EDIT = 12007;
const int ID2_MENU = 12008;
const int ID2_POINTS = 12009;
const int ID2_PAGE = 12010;
const int ID2_PREVIOUS = 12011;
const int ID2_PREVIOUS1 = 12012;
const int ID2_PREVIOUS2 = 12013;
const int ID2_NEXT = 12014;
const int ID2_NEXT1 = 12015;
const int ID2_NEXT2 = 12016;
const int ID2_GOTO1 = 12017;
const int ID2_GOTO2 = 12018;
const int ID2_TOOLS = 12019;
const int ID2_SUPERIMPOSE = 12020;
wxMenuBar *MenuBarFunc2();

// Declare toolbar functions

void ToolBarFunc2( wxToolBar *parent );

// Declare bitmap functions

wxBitmap BitmapsFunc2( size_t index );

#endif

// End of generated file
