//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: mus.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_mus_H__
#define __WDR_mus_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "mus_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

extern wxSizer *ToolNotesPaneBoxSizer;
const int ID_MS_BT_NOTES = 20000;
const int ID_MS_BT_KEY = 20001;
const int ID_MS_BT_SIGNS = 20002;
const int ID_MS_BT_SYMBOLES = 20003;
const int ID4_LINE = 20004;
const int ID_MS_BT_INSERT = 20005;
const int ID_MS_BT_N0 = 20006;
const int ID_MS_BT_N1 = 20007;
const int ID_MS_BT_N2 = 20008;
const int ID_MS_BT_N3 = 20009;
const int ID_MS_BT_N4 = 20010;
const int ID_MS_BT_N5 = 20011;
const int ID_MS_BT_N6 = 20012;
const int ID_MS_BT_N7 = 20013;
const int ID_MS_BT_R0 = 20014;
const int ID_MS_BT_R1 = 20015;
const int ID_MS_BT_R2 = 20016;
const int ID_MS_BT_R3 = 20017;
const int ID_MS_BT_R4 = 20018;
const int ID_MS_BT_R5 = 20019;
const int ID_MS_BT_R6 = 20020;
const int ID_MS_BT_CT = 20021;
const int ID_MS_BT_LG_D = 20022;
const int ID_MS_BT_LG_U = 20023;
const int ID_MS_BT_COLOR = 20024;
const int ID_MS_BT_UPDOWN = 20025;
wxSizer *NotesPanel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *ToolKeysPanelBoxSizer;
const int ID_MS_BT_G1 = 20026;
const int ID_MS_BT_G2 = 20027;
const int ID_MS_BT_U1 = 20028;
const int ID_MS_BT_U2 = 20029;
const int ID_MS_BT_U3 = 20030;
const int ID_MS_BT_U4 = 20031;
const int ID_MS_BT_U5 = 20032;
const int ID_MS_BT_F3 = 20033;
const int ID_MS_BT_F4 = 20034;
const int ID_MS_BT_F5 = 20035;
wxSizer *ClefsPanel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *ToolSignsPanelBoxSizer;
const int ID_MS_BT_MTPP = 20036;
const int ID_MS_BT_MTPDP = 20037;
const int ID_MS_BT_MTP = 20038;
const int ID_MS_BT_MTPD = 20039;
const int ID_MS_BT_MTIP = 20040;
const int ID_MS_BT_MTIDP = 20041;
const int ID_MS_BT_MTI = 20042;
const int ID_MS_BT_MTID = 20043;
const int ID_MS_BT_MTI2P = 20044;
const int ID_MS_BT_MTI2DP = 20045;
const int ID_MS_BT_MTI2 = 20046;
const int ID_MS_BT_MTI2D = 20047;
const int ID_MS_BT_M32 = 20048;
const int ID_MS_BT_M3 = 20049;
const int ID_MS_BT_M2 = 20050;
wxSizer *SignsPanel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

extern wxSizer *ToolSymbolesPanelBoxSizer;
const int ID_MS_BT_PNT = 20051;
const int ID_MS_BT_DIESE = 20052;
const int ID_MS_BT_BECAR = 20053;
const int ID_MS_BT_BEMOL = 20054;
const int ID_MS_BT_DDIESE = 20055;
const int ID_MS_BT_DBEMOL = 20056;
const int ID_MS_BT_BAR = 20057;
const int ID_MS_BT_RDOTS = 20058;
wxSizer *SymbolsPanel( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MS_EDIT1 = 20059;
const int ID_MS_CLEFS = 20060;
const int ID_MS_G1 = 20061;
const int ID_MS_G2 = 20062;
const int ID_MS_U1 = 20063;
const int ID_MS_U2 = 20064;
const int ID_MS_U3 = 20065;
const int ID_MS_U4 = 20066;
const int ID_MS_U5 = 20067;
const int ID_MS_F3 = 20068;
const int ID_MS_F4 = 20069;
const int ID_MS_F5 = 20070;
const int ID_MS_NOTES = 20071;
const int ID_MS_N0 = 20072;
const int ID_MS_N1 = 20073;
const int ID_MS_N2 = 20074;
const int ID_MS_N3 = 20075;
const int ID_MS_N4 = 20076;
const int ID_MS_N5 = 20077;
const int ID_MS_N6 = 20078;
const int ID_MS_N7 = 20079;
const int ID_MS_RESTS = 20080;
const int ID_MS_R0 = 20081;
const int ID_MS_R1 = 20082;
const int ID_MS_R2 = 20083;
const int ID_MS_R3 = 20084;
const int ID_MS_R4 = 20085;
const int ID_MS_R5 = 20086;
const int ID_MS_R6 = 20087;
const int ID_MS_R7 = 20088;
const int ID_MS_CT = 20089;
const int ID_MS_SIGNS = 20090;
const int ID_MS_MTPP = 20091;
const int ID_MS_MTPDP = 20092;
const int ID_MS_MTP = 20093;
const int ID_MS_MTPD = 20094;
const int ID_MS_MENU = 20095;
const int ID_MS_MTIP = 20096;
const int ID_MS_MTIDP = 20097;
const int ID_MS_MTI = 20098;
const int ID_MS_MTID = 20099;
const int ID_MS_MTI2P = 20100;
const int ID_MS_MTI2DP = 20101;
const int ID_MS_MTI2 = 20102;
const int ID_MS_MTI2D = 20103;
const int ID_MS_M32 = 20104;
const int ID_MS_M3 = 20105;
const int ID_MS_M2 = 20106;
const int ID_MS_SYMBOLS = 20107;
const int ID_MS_PNT = 20108;
const int ID_MS_DIESE = 20109;
const int ID_MS_BECAR = 20110;
const int ID_MS_BEMOL = 20111;
const int ID_MS_DDIESE = 20112;
const int ID_MS_DBEMOL = 20113;
const int ID_MS_BAR = 20114;
wxMenuBar *MsEditMenuFunc();

// Declare toolbar functions

// Declare bitmap functions

wxBitmap Clefs( size_t index );

wxBitmap Notes( size_t index );

wxBitmap Silences( size_t index );

wxBitmap Signs( size_t index );

wxBitmap Symbols( size_t index );

wxBitmap Btn( size_t index );

wxBitmap Btn_selected( size_t index );

#endif

// End of generated file
